apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: harbor
    app.kubernetes.io/managed-by: Helm
    chart: harbor
    component: registry
    heritage: Helm
    release: harbor
  name: harbor-registry
  namespace: harbor
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-5061852a-e96d-42d5-8910-ece408a921f1