# Generated by Django 4.0.6 on 2023-01-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_geslo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifipassword',
            name='ssid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
